# Generated by Django 4.2.7 on 2025-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10)),
                ('checkout_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10)),
                ('checkin_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('checkin_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('checkout_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('checkout_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-checkin_time'],
            },
        ),
    ]
