# Generated by Django 5.2.4 on 2025-07-07 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_shift_attendance_shift'),
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='guards', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='guard',
            name='weekend_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), blank=True, default=list, size=None),
        ),
    ]
