# Generated by Django 5.2.4 on 2025-07-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_guard_shifts_guard_weekend_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='weekend_days',
            field=models.TextField(blank=True, default=''),
        ),
    ]
