# Generated by Django 5.2.4 on 2025-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0003_alter_guard_weekend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='geofence_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='geofence_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Radius in meters', null=True),
        ),
    ]
